Repository gazebosim/gz-tools, pull requests merged in 2020-05, with the labels that each got.

#16 [ign-tools0] Workflow updates
  .github/CODEOWNERS
  .github/workflows/ci-bionic.yml
  .github/workflows/pr-collection-labeler.yml
  .github/workflows/triage.yml
  codecov.yml
Labels: 📜 blueprint

#17 [ign-tools1] Workflow updates
  .github/CODEOWNERS
  .github/workflows/ci-bionic.yml
  .github/workflows/pr-collection-labeler.yml
  .github/workflows/triage.yml
  codecov.yml
Labels: 🏰 citadel, 🔮 dome

#15 When using help, append --help to target command
  src/ign.in
Labels: bug
