Repository gazebosim/gz-tools, pull requests merged in 2021-03, with the labels that each got.

#42 Master branch updates
  .github/workflows/ci.yml
  README.md
Labels: 🏢 edifice, 🏰 citadel, 🔮 dome

#40 Clean up ignition-tools.pc file
  CMakeLists.txt
  cmake/pkgconfig/ignition.in
Labels: beta, 🏢 edifice, 🏰 citadel, 🔮 dome

#45 Use ; as IGN_CONFIG_PATH delimiter on windows
  src/CMakeLists.txt
  src/ign.in
Labels: Windows, beta, bug, 🏢 edifice, 🏰 citadel, 🔮 dome

#46 🎈 1.1.0~pre1
  CMakeLists.txt
  Changelog.md
Labels: 🏢 edifice, 🏰 citadel, 🔮 dome

#47 🎈 1.1.0
  CMakeLists.txt
  Changelog.md
Labels: 🏢 edifice, 🏰 citadel, 🔮 dome
