Repository gazebosim/gz-tools, pull requests merged in 2022-05, with the labels that each got.

#89 ign -> gz Namespace Migration : gz-tools
  src/backward.cc
Labels: 🌱 garden, ign to gz

#88 Merge ign-tools1 -> main
  CMakeLists.txt
  etc/ign.bash_completion.sh
Labels: 🌱 garden

#91 Remove unused config.hh.in
  cmake/config.hh.in
Labels: 🏰 citadel, 🏯 fortress

#92 Merge ign-tools1 ➡️ main
  cmake/config.hh.in
Labels: 🌱 garden

#90 Standardize config macros
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  Changelog.md
  Migration.md
  NEWS
  README.md
  doc/header.html
  doc/mainpage.html
  src/CMakeLists.txt
  src/ign.in
Labels: 🌱 garden, ign to gz
