Repository gazebosim/gz-tools, pull requests merged in 2022-08, with the labels that each got.

#106 Improve tab completion behavior when there are no libraries installed
  etc/gz.completion
  etc/ign.bash_completion.sh
Labels: 🏰 citadel, 🏯 fortress, OOBE 📦✨

#107 🎈 1.5.0
  CMakeLists.txt
  Changelog.md
Labels: 🏰 citadel, 🏯 fortress

#108 1 ➡️ 2
  CMakeLists.txt
  Changelog.md
  etc/CMakeLists.txt
  etc/gz.bash_completion.sh
  etc/gz.completion
Labels: bug, 🌱 garden

#109 Remove ign CLI from version 2
  Migration.md
  src/CMakeLists.txt
Labels: 🌱 garden, ign to gz
