Repository gazebosim/gz-tools, pull requests merged in 2022-04, with the labels that each got.

#83 Remove configure.bat
  configure.bat
Labels: 🏰 citadel, Windows, 🏯 fortress, 🌱 garden

#84 Revert "Remove configure.bat (#83)"
  configure.bat
Labels: 🏰 citadel, 🏯 fortress, 🌱 garden

#85 bump cmake to 2.8.12
  CMakeLists.txt
Labels: 🏰 citadel, 🏯 fortress

#86 Fix typo in bash completion, add help completion
  etc/ign.bash_completion.sh
Labels: 🏰 citadel, 🏯 fortress, OOBE 📦✨
