Repository gazebosim/gz-tools, pull requests merged in 2022-06, with the labels that each got.

#87 Bash completion for subcommand flags
  CMakeLists.txt
  etc/CMakeLists.txt
  etc/gz.completion
  etc/ign.bash_completion.sh
Labels: 🏰 citadel, 🏯 fortress, OOBE 📦✨

#95 Merge ign-tools1 ➡️ main
  CMakeLists.txt
  etc/CMakeLists.txt
  etc/gz.completion
  etc/ign.bash_completion.sh
Labels: 🌱 garden

#94 ign -> gz CLI Migration : gz-tools
  Migration.md
  README.md
  cmake/run_test.cmake
  etc/CMakeLists.txt
  etc/gz.bash_completion.sh
  src/CMakeLists.txt
  src/UNIT_gz_TEST.yaml.in
  src/cmdUNIT_gz_TEST.rb
  src/gz.bat
  src/gz.in
  tools/junit_fail.xml.in
  tools/junit_pass.xml.in
Labels: 🌱 garden, ign to gz

#96 Use gz-cmake
  .github/ci/packages.apt
  CMakeLists.txt
  Migration.md
  README.md
  cmake/DissectVersion.cmake
  cmake/SearchForStuff.cmake
  cmake/Utils.cmake
  cmake/cmake_uninstall.cmake.in
  cmake/cpack.cmake
  cmake/cpack_options.cmake.in
  cmake/ignition-config.cmake.in
  cmake/pkgconfig/ignition.in
  configure.bat
  doc/CMakeLists.txt
  doc/doxygen.css
  doc/footer.html
  doc/header.html
  doc/ignition.in
  doc/ignition_logo.png
  doc/ignition_logo.svg
  doc/mainpage.html
  doc/search.js
  doc/style.css
  src/CMakeLists.txt
  src/backward.cc
  src/gz.in
  tools/.rubocop.yml
  tools/code_check.sh
  tutorials.md.in
  tutorials/install.md
Labels: 🌱 garden, ign to gz

#93 Rename CMake project to gz
  CMakeLists.txt
Labels: 🌱 garden, ign to gz

#98 ign -> gz Partial Docs Migration and Project Name Followups : gz-tools
  Changelog.md
  Migration.md
  tutorials/install.md
Labels: 🌱 garden
